### ISSUE TITLE
Inkscape unsaved file issue

### ISSUE THREAD

**Issue by jfowlie** [fablabnbg/inkscape-paths2openscad#15]
I wonder if it is possible to add a test to see if the file has been saved in Inkscape before attempting to generate the paths to OpenSCAD. I just spent an hour trying to walk the code (and I don't know Python), only to realize that I had not saved the file I had created in Inkscape before trying to export to OpenSCAD.

I kept getting these errors:
Traceback (most recent call last):
  File "paths2openscad.py", line 1430, in <module>
    e.affect()
  File "/usr/share/inkscape/extensions/inkex.py", line 283, in affect
    self.effect()
  File "paths2openscad.py", line 1213, in effect
    self.handleViewBox()
  File "paths2openscad.py", line 594, in handleViewBox
    if self.getDocProps():
  File "paths2openscad.py", line 580, in getDocProps
    self.inkscape_version = re.sub(" *\(unknown\) *", "", inkscape_version)
  File "/usr/lib/python2.7/re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer

Thanks for your work on this! I hope to make a lot more use of it.
--James

**Comment by vmario89** [comment]
hey. indeed happened to me too fequently. The dirty quick fix is to change

> self.inkscape_version = re.sub(" *\(unknown\) *", "", inkscape_version)

to 
>  self.inkscape_version = "0.92.4"

then it works. regards, Mario

**Comment by vmario89** [comment]
okay might be more complex, because this is belonging to https://github.com/fablabnbg/paths2openscad/issues/1
